id: fix_ui_bug
hints:
  - Try to find what all the users that drop in the funnel have in common
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Now that we have all the info about the bug, let's open a fix PR"
            delay: 2000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "Thanks @${user.githubuser}, I'll review the changes right away!"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "Excellent job ${user.firstName}! You're now able to merge the PR."
                    delay: 1300
            - actionId: github_pr_approve
              params:
                person: head-of-rd
                message: "Excellent job @${user.githubuser}! You're now able to merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Make sure all checks pass, only then you can merge the PR.

            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Make sure all checks pass, only then you can merge the PR.
                    delay: 2500
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  frontend:
    capabilities: []
    testFile: "frontend.test.js"