id: intro
hints:
  - Try to find what all the users that drop in the funnel have in common
startFlow:
  do:
    - actionId: github_open_issue
      params:
        title: "#INC-5312: Missing image"
        body: |
          It seems that when creating a new product without an image, there are broken images showing up in the product catalog. 
          
          Try and reproduce this issue locally by creating some imageless items, and then make sure that the frontend always renders a placeholder image. 
          
          You can find a placeholder image in the repository, it's called `placeholder.png`.
          Once you fix this issue, open a PR and attach a screenshot of the fixed UI.    - actionId: bot_message
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "So, as I mentioned before, we have a critical bug in production that needs fixing."
            delay: 2000
          - text: "I'm opening an [issue on our Github repository](${user.repository}/issues) and assigning it to you - so you can have a look. Please fix it ASAP, and remember to submit a PR once you’re done."
            delay: 4500
          - text: "Oh, and in case you feel like you need to read more about this, I got you covered ;) - you can click [here](https://trywilco.notion.site/Simulation-3-Partial-data-84f002db325747028f10df61a0d95d11) for more useful information. "
            delay: 2000
          - text: "Do you feel ready to tackle this bug? Let me know if you'd like further guidance about this task"
            delay: 10200
          - components:
              - type: form
                form:
                  id: more_info
                  type: single_select_form
                  select_limit: 1
                  options:
                    - value: yes
                      label: Can you elaborate?
                      variant: primary # optional, default: primary

                    - value: no
                      label: "I'm good"
                      variant: secondary

trigger:
  type: chat_form_submitted
  params:
    formId: more_info
  flowNode:
    if:
      conditions:
        - conditionId: text_contains_strings
          params:
            text: "${{formSubmission}}"
            strings:
              - yes
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
                - text: "Sure! Let's start by understanding the bug"
                  delay: 2000
                - text: "To fix this bug, you will need to identify the root cause and take the appropriate action. This may involve checking the file path, ensuring the image is in a supported format and not corrupt, verifying the encoding, or troubleshooting the server or network connection."
                  delay: 2000
          - actionId: finish_step
      else:
        do:
          - actionId: finish_step